---
type: dev
name: dev
dirs:
    - ENSTDkAm
path: /Users/sandervandenhaute/Documents/speech/piano/data/
cache: /Users/sandervandenhaute/Documents/speech/piano/cache/
test: /Users/sandervandenhaute/Documents/speech/piano/test/
files_to_load: 1
sample_rate: 16000
spec_hop_length: 512
spec_fmin: 21
spec_n_bins: 229
cqt_bins_per_octave: 36
channels: 1
spec_mel_htk: True
n_fft: 2048
onset_slack: 50 # allowed slack in onset time (in ms)
onset_length: 32 # minimum onset time
length_slack_ms: 50 # allowed slack in note lengths (in ms)
length_slack_percent: 20 # allowed slack in note lengths (in percentage)
create_tfrecords: False
batch_size: 2
sequence_length: 60
lstm_units: 128
loss_epsilon: 1.0e-7
learning_rate: 0.0006
clip_norm: 3.0
threshold: 0.5
iters: 30
test_iters: 5
verbose: 1

plot_duration: 10
...
