---
type: dev
name: dev
dirs:
    - ENSTDkAm
path: /Users/sandervandenhaute/Documents/speech/piano/data/
files_to_load: 1
sample_rate: 16000
spec_hop_length: 512
spec_fmin: 21
spec_n_bins: 229
cqt_bins_per_octave: 36
channels: 1
spec_mel_htk: True
n_fft: 2048
onset_slack: 50 # allowed slack in onset time (in ms)
length_slack_ms: 50 # allowed slack in note lengths (in ms)
length_slack_percent: 20 # allowed slack in note lengths (in percentage)
...
